on:
  schedule:
  - cron: 0 0 * * 3
name: Update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: duplessi.geoffrey@gmail.com
        AUTHOR_NAME: Grezor
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.UPDATE }}
      with:
        args: -u --packageFile package.json  --dep dev